[build-system]
requires = ["poetry-core>=1.1.0a7"]
build-backend = "poetry.core.masonry.api"


[tool.poetry]
name = "blab-chatbot-deepage"
version = "0.0.1dev"
description = ""
authors = ["C4AI"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
datasets = "^2.2.2"
transformers = {extras = ["torch"], version = "^4.19.2"}
fsspec = "^2022.5.0"
sentencepiece = "^0.1.96"
elasticsearch = "^8.2.0"

[tool.poetry.group.dev.dependencies]
black = "^22.3.0"

